name: CI

on: [push, pull_request]

env:
    DEFAULT_COMPOSER_FLAGS: --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist

jobs:
    build:
        runs-on: Ubuntu-20.04
        strategy:
            matrix:
              php: ['7.1', '7.2']
              DEPENDENCIES: ['', '--prefer-lowest']
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy
              if: ${{ matrix.php == 7.2 && matrix.DEPENDENCIES == '' && contains(github.ref, 'tag')}}
              run: echo "Update schema" ${{ github.ref }}
              
            - name: Step 1 - Echo out a GitHub Actions Secret to the logs
              run: |
                  echo "The GitHub Action Secret will be masked:  "
                  echo ${{ secrets.GITHUB_TOKEN }}
                  echo "Trick to echo GitHub Actions Secret:  "
                  echo ${{secrets.GITHUB_TOKEN}} | sed 's/./& /g' 
      
            - name: Update Schema
              if: ${{ matrix.php == 7.2 && matrix.DEPENDENCIES == ''}}
              run: |
                  sudo chmod +775 schema.sh
                  ./schema.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
