name: CI

on: [push, pull_request]

env:
    DEFAULT_COMPOSER_FLAGS: --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist

jobs:
    build:
        runs-on: Ubuntu-20.04
        strategy:
            matrix:
              php: ['7.1', '7.2']
              DEPENDENCIES: ['', '--prefer-lowest']
        steps:
            - name: Deploy
              if: ${{ matrix.php == 7.4 && matrix.DEPENDENCIES == '' && contains(github.ref, 'tag')}}
              run: echo "Update schema" ${{ github.ref }}

            - name: Checkout
              run: echo "Update schema" ${{ github.ref }} ${{ matrix.DEPENDENCIES }}

            - name: Update Schema
              if: ${{ matrix.php == 7.4 && matrix.DEPENDENCIES == ''}}
              run: |
                  sudo chmod +775 schema.sh
                  ./schema.sh
