name: Schema

on:
    - push
    
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.3


            - name: Build docker
              run: |
                  cd /home/runner/work/
                  git clone --depth 1 https://github.com/OXID-eSales/docker-eshop-sdk.git
                  cd docker-eshop-sdk
                  make .env
                  sed "s/PHP_VERSION=.*/PHP_VERSION=7.3/" -i .env
                  git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch b-6.2.x --single-branch data/oxideshop
                  mkdir data/oxideshop/debug
                  make permissions
                  make data/oxideshop/vendor/
                  make data/oxideshop/source/config.inc.php
                  docker-compose up -d php
                  sleep 10
                  make reset-db
                  
            - name: Prepare shop
              run: |
                  sudo npm install -g @2fd/graphdoc
                  cd /home/runner/work/docker-eshop-sdk/data/oxideshop/
                  cp -r $GITHUB_WORKSPACE graphql-base-module
                  docker-compose exec -T --user oxid php composer require oxid-esales/graphql-base --prefer-source
                  docker-compose exec -T --user oxid php composer require oxid-esales/graphql-storefront
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:install-configuration source/modules/oe/graphql-base/
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:install-configuration source/modules/oe/graphql-storefront/
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:activate oe_graphql_base
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:activate oe_graphql_storefront
                  
            - name: Generate documentation
              run: |
                  cd /home/runner/work/docker-eshop-sdk/data/oxideshop/
                  ls -l
                  cd vendor/oxideshop-ce
                  ls -l
                  cd oxideshop-ce
                  ls -l
                  cp vendor/oxid-esales/graphql-base/graphdocs.php .
                  php -S localhost:8080 &
                  sleep 2;
                  TOKEN=$(curl --silent http://localhost:8080/graphdocs.php?skipSession=1 -H 'Content-Type: application/json' --data-binary '{"query":"query {token(username: \"admin\", password:\"admin\")}"}' | sed -n 's|.*"token":"\(.*\)\"}}|\1|p')
                  #graphdoc -e http://localhost:8080/graphdocs.php?skipSession=1 -o $GITHUB_WORKSPACE/docs/_static/schema -f -x "Authorization: Bearer $TOKEN"
