name: Schema

on:
    - push
    
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.3


            - name: Build docker
              if: ${{ matrix.php != '7.1' && env.DEPENDENCIES == '' }}
              run: |
                  cd /home/runner/work/
                  git clone --depth 1 https://github.com/OXID-eSales/docker-eshop-sdk.git
                  cd docker-eshop-sdk
                  make .env
                  sed "s/PHP_VERSION=.*/PHP_VERSION=${{ matrix.php }}/" -i .env
                  git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch b-6.2.x --single-branch data/oxideshop
                  mkdir data/oxideshop/debug
                  make permissions
                  make data/oxideshop/vendor/
                  make data/oxideshop/source/config.inc.php
                  docker-compose up -d php
                  sleep 10
                  make reset-db
                  
            - name: Prepare shop and run codeception in docker
              if: ${{ matrix.php != '7.1' && env.DEPENDENCIES == '' }}
              run: |
                  cd /home/runner/work/docker-eshop-sdk/data/oxideshop/
                  cp -r $GITHUB_WORKSPACE graphql-base-module
                  docker-compose exec -T --user oxid php composer config repositories.grapqhl-base path ./graphql-base-module/
                  docker-compose exec -T --user oxid php composer require oxid-esales/graphql-base
                  docker-compose exec -T --user oxid php composer require codeception/module-rest --dev
                  docker-compose exec -T --user oxid php composer require codeception/module-phpbrowser --dev
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:install-configuration source/modules/oe/graphql-base/
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:activate oe_graphql_base
                  docker-compose exec -T --user oxid php composer require codeception/c3 --dev
                  sed -i 's/<?php/<?php\n\nrequire(__DIR__ . "\/..\/c3.php");/' source/bootstrap.php
