name: Schema

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: Ubuntu-20.04
        env:
            php: 7.4

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.php }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Build docker
              run: |
                  cd /home/runner/work/
                  git clone --depth 1 https://github.com/OXID-eSales/docker-eshop-sdk.git --branch master-xdebug_nesting_level
                  cd docker-eshop-sdk
                  make .env
                  sed "s/PHP_VERSION=.*/PHP_VERSION=${{ env.php }}/" -i .env
                  echo "XDEBUG_NESTING_LEVEL=512" >> .env
                  git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch master --single-branch data/oxideshop
                  mkdir data/oxideshop/debug
                  make permissions
                  make data/oxideshop/vendor/
                  make data/oxideshop/source/config.inc.php
                  docker-compose up -d php
                  sleep 10
                  make reset-db

            - name: Prepare shop
              run: |
                  cd /home/runner/work/docker-eshop-sdk/data/oxideshop/
                  docker-compose exec -T --user oxid php composer require oxid-esales/graphql-base:dev-master-upgrade_to_graphqlite_v4-OXDEV-4383
                  docker-compose exec -T --user oxid php composer require oxid-esales/graphql-storefront:dev-master-upgrade_graphql_v4
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:install vendor/oxid-esales/graphql-base/
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:install vendor/oxid-esales/graphql-storefront/
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:activate oe_graphql_base
                  docker-compose exec -T --user oxid php php bin/oe-console oe:module:activate oe_graphql_storefront

            - name: Generate documentation
              run: |
                  sudo npm install -g @2fd/graphdoc
                  cd /home/runner/work/docker-eshop-sdk/data/oxideshop/
                  sleep 2;
                  graphdoc -e http://localhost/graphql?skipSession=1 -o $GITHUB_WORKSPACE/docs/_static/schema -f

#             - name: Setup tmate session
#               if: always()
#               uses: mxschmitt/action-tmate@v3

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  BRANCH: schema
                  FOLDER: docs/_static/schema

